name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:	
    branches:
      - main
  jobs:	
    build:
         runs-on: ubuntu-latest
    steps:
     - name: Checkout  do repositorio
       uses: actions/checkout@v3

     - name: Listar arquivos para verificar diretorio
       run: ls -R

     - name: Configurar JDK 18
       uses: actions/setup-java@v3
       
       with:
        distribution: 'temurin'
        java-version: '18'
     - name: "Compilar projeto com Maven"
       working-directory: ./demo # Caminho correto para o seu pom.xml
       run: mvn compile
