name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # Listar arquivos e diretórios (debug)
      - name: Listar arquivos para verificar diretório
        run: ls -R

      # Configura Java 11
      - name: Configurar JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      # Rodar o Maven para construir o projeto
      - name: Compilar projeto com Maven
        working-directory: ./mavenproject1   # Caminho correto para o seu pom.xml
        run: mvn clean install

      # Adicionar um teste básico para rodar a compilação
      - name: Verificar o build
        working-directory: ./demo  # Garante que o Maven rode no diretório correto
        run: mvn compile